FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# bks

ユーザーと物品は1対多なので、
紐付の情報は物品側に寄せました。

## ユーザのエンドポイント [/users]
 
### ユーザ登録 [POST]
 
#### 処理概要
 
* ユーザ情報を新しく登録する。
* IDが重複する場合エラーで400を返す(変更はデリート→インサートでのみ)
* 入力エラーも400を返す
 
+ Request (application/json)
 
    + Headers
 
            Accept: application/json
 
    + Attributes
        + userId: RTCP0000001 (string, required) - ユーザーID（pattern: ^[0-9A-Za-z]{11}$）
        + name: 山田 太郎 (string, required) - 名前（pattern: ^.{1,30}$）
        
+ Response 201 (application/json)
 


### ユーザ情報全件取得 [GET /users]

#### 処理概要
 
* 登録してあるユーザー情報を全件取得

+ Request (application/json)
 
    + Headers
 
            Accept: application/json

+ Response 200 (application/json)
 
    + Attributes
        + users (array)
            + (object)
                + userId: RTCP0000001 (string, required) - ユーザーID
                + name:  山田 太郎 (string, required) - 名前
                + registered: `2016-12-16T08:00:00+09:00` (string, required) - 登録日  (ISO 8601形式)




### ユーザ情報1件取得 [GET /users/{userId}]

#### 処理概要
 
* 指定されたユーザー情報を取得
* 指定されたユーザーIDが存在しなければエラーで400返す


    
+ Parameters
 
   + userId: RTCP0000001 (string, required) - ユーザーID

+ Request (application/json)
 
    + Headers
 
            Accept: application/json

+ Response 200 (application/json)
 
    + Attributes
        + user (object)
            + userId: RTCP0000001 (string, required) - ユーザーID
            + name:  山田 太郎 (string, required) - 名前
            + registered: `2016-12-16T08:00:00+09:00` (string, required) - 登録日  (ISO 8601形式)



### ユーザ削除 [DELETE /users/{userId}]


#### 処理概要
 
* 指定されたユーザー情報を削除
* 指定されたユーザーIDが存在しなければそのまま正常終了

+ Parameters
 
   + userId: RTCP0000001 (string, required) - ユーザーID
   
+ Request (application/json)
 
    + Headers
 
            Accept: application/json

+ Response 204 (application/json)





## 物品のエンドポイント [/equipment]


### 物品登録 [POST]
 
#### 処理概要
 
* 物品情報を新しく登録する。
* 登録時にequipmentIdを発番する。 - 物品ID（pattern: ^[0-9A-Za-z]{7}$）
* IDが重複する場合エラーで400を返す(変更はデリート→インサートでのみ)
* 入力エラーも400を返す
 
+ Request (application/json)
 
    + Headers
 
            Accept: application/json
 
    + Attributes
        + name: Mac Book Pro (string, required) - 名前（pattern: ^.{1,30}$）
        
+ Response 201 (application/json)

### 物品とユーザの紐付 [PATCH /equipment/{equipmentId}/users/{userId}]
 
#### 処理概要
 
* 物品情報を新しく登録する。
* IDが重複する場合エラーで400を返す(変更はデリート→インサートでのみ)
* 入力エラーも400を返す

+ Parameters
 
   + equipmentId: 0000001 (string, required) - 物品ID
   + userId: RTCP0000001 (string, required) - ユーザーID

+ Request (application/json)
 
    + Headers
 
            Accept: application/json

+ Response 201 (application/json)


### 物品情報全件取得 [GET /equipment]

#### 処理概要
 
* 登録してある物品情報を全件取得
* QRコード画像へアクセスするURLはレスポインスに含める(よしなに設定できるように)
* ユーザーと紐づいている場合、ユーザー情報を返却する

+ Request (application/json)
 
    + Headers
 
            Accept: application/json

+ Response 200 (application/json)
 
    + Attributes
        + equipment (array)
            + (object)
                + equipmentId: 0000001 (string, required) - 物品ID
                + name: Mac Book Pro (string, required) - 名前
                + registered: `2016-12-16T08:00:00+09:00` (string, required) - 登録日  (ISO 8601形式)
                + updated`2016-12-16T08:00:00+09:00` (string, required) - 更新日  (ISO 8601形式)
                + qrImageUrl /equipment/0000001/qrImages (string, required) - QRコードの画像にアクセスするURL
                + user (object)
                    + userId: RTCP0000001 (string, required) - ユーザーID
                    + name:  山田 太郎 (string, required) - 名前
                    + registered: `2016-12-16T08:00:00+09:00` (string, required) - 登録日 (ISO 8601形式)



### 物品情報1件取得 [GET /equipment/{equipmentId}]

#### 処理概要
 
* 指定された物品情報を取得
* 指定された物品IDが存在しなければエラーで400返す
* QRコード画像へアクセスするURLはレスポインスに含める(よしなに設定できるように)
* ユーザーと紐づいている場合、ユーザー情報を返却する

    
+ Parameters
 
   + equipmentId: 0000001 (string, required) - 物品ID

+ Request (application/json)
 
    + Headers
 
            Accept: application/json


+ Response 200 (application/json)
 
    + Attributes
        + equipment (object)
            + equipmentId: 0000001 (string, required) - 物品ID
            + name: Mac Book Pro (string, required) - 名前
            + registered: `2016-12-16T08:00:00+09:00` (string, required) - 登録日 (ISO 8601形式)
            + updated`2016-12-16T08:00:00+09:00` (string, required) - 更新日  (ISO 8601形式)
            + qrImageUrl /equipment/0000001/qrImages (string, required) - QRコードの画像にアクセスするURL
            + user (object)
                + userId: RTCP0000001 (string, required) - ユーザーID
                + name:  山田 太郎 (string, required) - 名前
                + registered: `2016-12-16T08:00:00+09:00` (string, required) - 登録日  (ISO 8601形式)



### 物品削除 [DELETE /equipment/{equipmentId}]


#### 処理概要
 
* 指定された物品情報を削除
* 指定された物品IDが存在しなければそのまま正常終了

+ Parameters
 
   + equipmentId: 0000001 (string, required) - 物品ID

+ Request (application/json)
 
    + Headers
 
            Accept: application/json

+ Response 204 (application/json)